//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessAnimalGame.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int Id { get; set; }
        public string AnimalDescription { get; set; }
        public string HasQuestion { get; set; }
        public string BehaviourQuestion { get; set; }
        public string IsQuestion { get; set; }
    }
}
